[package]
name = "stellar_manifest"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/quantumatic/stellar"
authors = ["Adi Salimgereyev <adisalimgereev@gmail.com>"]
readme = "../../README.md"
description = "Parses and processes Stellar projects' configuration files."

[dependencies]
serde = { version = "1.0.167", features = ["derive"] }
serde_ignored = "0.1.8"
toml = "0.8.0"
toml_edit = "0.21.0"
